### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by paulhaem** [trufflesuite/ganache#1225]
I just deployed my new contract and wanted to view it in the contracts section and then occured this error. Any tipps on how to avoid this?

PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:154:73)
    at Array.map (native)
    at allocateContract (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:154:61)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:28:23)
    at TruffleContractDecoder.init (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:87:43)
    at Object.getContractState (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\decode.js:18:11)
    at process.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\index.js:76:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"C:\\Users\\AlexanderHämmerle\\AppData\\Roaming\\Ganache\\workspaces\\ehr-platform\\chaindata"}
T+200ms: Ganache started successfully!
T+200ms: Waiting for requests...
T+216ms: eth_getCode
T+234ms: eth_subscribe
T+246ms: eth_getLogs
T+264ms: eth_subscribe
T+277ms: eth_getCode
T+8965ms: eth_unsubscribe
T+8995ms: eth_unsubscribe
T+9012ms: eth_unsubscribe
T+9028ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have an issues or if the fix doesn't work for you.

**Comment by paulhaem** [comment]
Sadly the fix didn't work for me. :(

PLATFORM: win32
GANACHE VERSION: 2.0.1-beta.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:154:73)
    at Array.map (native)
    at allocateContract (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:154:61)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:28:23)
    at TruffleContractDecoder.init (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:87:43)
    at Object.getDecodedEvent (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\decode.js:42:11)
    at process.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+40ms: eth_unsubscribe
T+40ms: eth_unsubscribe
T+40ms: eth_unsubscribe
T+40ms: eth_unsubscribe
T+563ms: Starting server (version 2.0.1-beta.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","db_path":"C:\\Users\\AlexanderHämmerle\\AppData\\Roaming\\Ganache\\workspaces\\ablaze-liquid\\chaindata","default_balance_ether":100,"hostname":"127.0.0.1","locked":false,"network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"verbose":false,"vmErrorsOnRPCResponse":true}
T+733ms: Ganache started successfully!
T+733ms: Waiting for requests...
T+749ms: eth_getCode
T+758ms: eth_subscribe
T+773ms: eth_getLogs
T+788ms: eth_subscribe
T+822ms: eth_getCode
T+78231ms: net_version
T+78309ms: eth_accounts
T+78375ms: eth_getBlockByNumber
T+78417ms: eth_getBlockByNumber
T+78461ms: eth_call
T+199333ms: net_version
T+199404ms: eth_accounts
T+199476ms: eth_getBlockByNumber
T+199524ms: eth_getBlockByNumber
T+199583ms: eth_call
T+238198ms: net_version
T+238262ms: eth_accounts
T+238318ms: eth_getBlockByNumber
T+238369ms: eth_getBlockByNumber
T+238450ms: eth_call
T+251859ms: net_version
T+251921ms: eth_accounts
T+251984ms: eth_getBlockByNumber
T+252017ms: eth_getBlockByNumber
T+252052ms: eth_call
T+309355ms: net_version
T+309433ms: eth_accounts
T+309485ms: eth_getBlockByNumber
T+309534ms: eth_accounts
T+309574ms: eth_getBlockByNumber
T+309624ms: eth_getBlockByNumber
T+309675ms: eth_getBlockByNumber
T+309740ms: eth_estimateGas
T+309783ms: eth_getBlockByNumber
T+309853ms: eth_blockNumber
T+309935ms: eth_sendTransaction
T+316533ms:   Transaction: 0xd85127c808e8df1cce95b94f0249818ae7b964bdf2357fb838dfc9914f840a40
T+316533ms:   Contract created: 0x48ef92a3960631bd33e12a35bc1bbdf6c3cebfd2
T+316533ms:   Gas usage: 273162
T+316577ms:   Block Number: 1
T+316577ms:   Block Time: Wed Apr 10 2019 21:54:03 GMT+0200 (W. Europe Daylight Time)
T+316594ms: eth_getBlockByNumber
T+316612ms: eth_getTransactionReceipt
T+316649ms: eth_getCode
T+316692ms: eth_getTransactionByHash
T+316731ms: eth_getBalance
T+316746ms: eth_getBlockByNumber
T+316767ms: eth_getBlockByNumber
T+316782ms: eth_sendTransaction
T+316805ms:   Transaction: 0xcbca4be422914a71dc73006c171b3f345e5e61d5fd566148fa5e97ae3065714f
T+316805ms:   Gas usage: 42028
T+316805ms:   Block Number: 2
T+316822ms:   Block Time: Wed Apr 10 2019 21:54:03 GMT+0200 (W. Europe Daylight Time)
T+316844ms: eth_getBlockByNumber
T+316855ms: eth_getTransactionReceipt
T+316878ms: eth_getBlockByNumber
T+316964ms: eth_accounts
T+316964ms: eth_getBlockByNumber
T+316964ms: eth_getBlockByNumber
T+316964ms: eth_getBlockByNumber
T+317060ms: eth_estimateGas
T+317060ms: eth_getBlockByNumber
T+317060ms: eth_blockNumber
T+317076ms: eth_sendTransaction
T+317100ms:   Transaction: 0x6a19d1b2b60882ed56a448e59c79fe1c206b676141c4f0ce6236b4970079ab7e
T+317100ms:   Contract created: 0x9458f142a8d35ce8615c6125c23b7f8c63195432
T+317100ms:   Gas usage: 2934187
T+317100ms:   Block Number: 3
T+317116ms:   Block Time: Wed Apr 10 2019 21:54:04 GMT+0200 (W. Europe Daylight Time)
T+317152ms: eth_getBlockByNumber
T+317152ms: eth_getTransactionReceipt
T+317176ms: eth_getCode
T+317198ms: eth_getTransactionByHash
T+317228ms: eth_getBalance
T+317245ms: eth_getBlockByNumber
T+317266ms: eth_getBlockByNumber
T+317282ms: eth_sendTransaction
T+317298ms:   Transaction: 0xde0899bc20d3a7923a35abe63184ab51cea75ba713949545d3c9fe361ddb94b6
T+317298ms:   Gas usage: 27028
T+317298ms:   Block Number: 4
T+317323ms:   Block Time: Wed Apr 10 2019 21:54:04 GMT+0200 (W. Europe Daylight Time)
T+317339ms: eth_getBlockByNumber
T+317360ms: eth_getTransactionReceipt
T+324324ms: eth_unsubscribe
T+324343ms: eth_unsubscribe
T+324367ms: eth_unsubscribe
T+324385ms: eth_unsubscribe
T+324385ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
_Now_ this issue should be fixed in the latest beta! https://github.com/trufflesuite/ganache/releases/tag/v2.0.2-beta.0

**Comment by paulhaem** [comment]
I still get an error, but a new one this time. In the storage section it says 'There was an issue decoding your contract.' Could it be that my contract code is causing some issues or firing some extraordinary exception? Thank you very much for your hard work so far. 😊

PLATFORM: win32
GANACHE VERSION: 2.0.2-beta.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 951$ of contract$ Platform (ID 714)
    at vars.concat.linearizedBaseContractsFromBase.map (C:\Program Files\WindowsApps\Ganache_2.0.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:158:19)
    at Array.map (native)
    at allocateContract (C:\Program Files\WindowsApps\Ganache_2.0.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:155:61)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\Ganache_2.0.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.0.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:113:47)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\WindowsApps\Ganache_2.0.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by davidmurdoch** [comment]
@paulhaem Hm. Interesting. From what I understand (@haltman-at, correct me if I'm wrong), the contract you've linked wasn't compiled by truffle so the truffle-decoder library can't parse it completely. If you re-compile your contracts with `truffle compile --all, or, if necessary, recompiling and redeploying the whole thing with `truffle migrate --compile-all --reset`, everything will work.

Does that sound like it could be what is happening here for you?

**Comment by paulhaem** [comment]
Wow, recompiling and redeploying the contract did the thing. Problem so far solved. Thank you very much!

**Comment by davidmurdoch** [comment]
@paulhaem was the contract original compiled with a different tool?

**Comment by paulhaem** [comment]
No, I started the project from begin on with truffle.

**Comment by haltman-at** [comment]
To offer a little clarity here -- the reason the recompile helps is because the allocator relies on certain IDs which aren't consistent across compilations; so it's not about, was it compiled with Truffle, but rather, were the files using these IDs compiled together, or were they compiled separately.  Now, of course, using separately-compiled contracts shouldn't crash Ganache, but, well, we failed to anticipate the problem initially.

I believe the crash is fixed in the latest beta -- but the error is still there, only now we just fail to decode rather than crashing Ganache.  Fixing the actual underlying error will take longer, I'm afraid.  Still, for now recompiling should work as a workaround.  Hopefully we get the actual problem solved before too long!

**Comment by paulhaem** [comment]
Thanks for the insight. You guys are doing a great work!

**Comment by davidmurdoch** [comment]
@haltman-at any thoughts on having Ganache do a recompile itself when adding the truffle project?

**Comment by haltman-at** [comment]
I mean, you could do that, I suppose, but I'd worry about performance; a full recompile can take a long time.  We tolerate it in the debugger because there's simply no way we can make the debugger work without it, but Ganache *mostly* doesn't need it, at least to my knowledge.  But whether you want to pay that penalty is up to you, I guess!  I think @gnidan had another reason he thought it was a bad idea which I don't quite remember -- I think basically it was, like, what if someone tinkers with their project a bit, opens Ganache to check something, and, oops, recompile happens!  IDK, you should talk to @gnidan about this.  Long story short, my suspicion is that it's a bad idea, but obviously it's not my area, don't take my word for it.

(If you do go down that road though, I'll have a bit of work to do making the contract decoder support decoding for internal function pointers; currently decoding those is only supported via the decoder's direct interface that the debugger uses, and not in the contract decoder, because trying to decode those is hopeless unless the whole project was compiled simultaneously, so I just didn't bother writing support for it unless you use the direct interface.  If users of the contract decoder start doing recompiles, I'll have to write code to support decoding those via the contract decoder, I guess. :P )
