### ISSUE TITLE
AssertionError: The field to must have byte length of 20 at FakeTransaction.setter

### ISSUE THREAD

**Issue by printlnBTC** [trufflesuite/ganache#231]
The following occurs during the sign transaction phase of myetherwallet

h_getTransactionCount
[3:20:37 PM] eth_estimateGas
[3:20:37 PM] 
[3:20:37 PM] C:\Program Files\WindowsApps\Ganache_1.0.1.0_x64__zh355ej5cj694\app\resources\app\node_modules\ethereumjs-testrpc\build\lib.node.js:63898
[3:20:37 PM] var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="fun
[3:20:37 PM] AssertionError: The field to must have byte length of 20
[3:20:37 PM]     at FakeTransaction.setter [as to] (C:\Program Files\WindowsApps\Ganache_1.0.1.0_x64__zh355ej5cj694\app\resources\app\node_modules\ethereumjs-testrpc\build\lib.node.js:7366:9)
[3:20:37 PM]     at C:\Program Files\WindowsApps\Ganache_1.0.1.0_x64__zh355ej5cj694\app\resources\app\node_modules\ethereumjs-testrpc\build\lib.node.js:7416:63
[3:20:37 PM]     at Array.forEach (native)
[3:20:37 PM]     at Object.exports.defineProperties (C:\Program Files\WindowsApps\Ganache_1.0.1.0_x64__zh355ej5cj694\app\resources\app\node_modules\ethereumjs-testrpc\build\lib.node.js:7415:14)
[3:20:37 PM]     at FakeTransaction.Transaction (C:\Program Files\WindowsApps\Ganache_1.0.1.0_x64__zh355ej5cj694\app\resources\app\node_modules\ethereumjs-testrpc\build\lib.node.js:78121:13)
[3:20:37 PM]     at FakeTransaction (C:\Program Files\WindowsApps\Ganache_1.0.1.0_x64__zh355ej5cj694\app\resources\app\node_modules\ethereumjs-testrpc\build\lib.node.js:20454:5)
[3:20:37 PM]     at C:\Program Files\WindowsApps\Ganache_1.0.1.0_x64__zh355ej5cj694\app\resources\app\node_modules\ethereumjs-testrpc\build\lib.node.js:80343:14
[3:20:37 PM]     at C:\Program Files\WindowsApps\Ganache_1.0.1.0_x64__zh355ej5cj694\app\resources\app\node_modules\ethereumjs-testrpc\build\lib.node.js:21924:5
[3:20:37 PM]     at C:\Program Files\WindowsApps\Ganache_1.0.1.0_x64__zh355ej5cj694\app\resources\app\node_modules\ethereumjs-testrpc\build\lib.node.js:55954:5
[3:20:37 PM]     at C:\Program Files\WindowsApps\Ganache_1.0.1.0_x64__zh355ej5cj694\app\resources\app\node_modules\ethereumjs-testrpc\build\lib.node.js:56320:14

PLATFORM: win32
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
--------------------------------------------------------------------------
pragma solidity ^0.4.0;

contract LiarsPokerRegistry {

    address listingAgent;
    uint16 numberOpenTables;
    bool isOpen;
    PokerTable[] public pokerRoom;
    bytes32 private constant EMPTY = "EMPTY";
    
    struct PokerTable {
        bytes32 channelName;
        address creator;
        uint tableStakes;
    }
    
    // event 
    
    function LiarsPokerRegistry() public {
        listingAgent = msg.sender;
        numberOpenTables = 10;
        isOpen = true;
        
        /**
        uint16 i;
        for (i = 0; i < _MAX_TABLES; i++) {
            pokerRoom.push(PokerTable({channelName: 'EMPTY', creator: address(0), tableStakes: 0}));
        }*/
    }
    
    /**
    function playChannel() public payable 
    returns () {
        require(isOpen);
    }*/
    
    
    modifier onlyBy(address _account) {
        require(msg.sender == _account);
        _;
    }
    
    function stop() public onlyBy(listingAgent) {
        // Could be nice and return the money on the open tables.
        // Currently, it is up to table owner to cancel his games
        isOpen = false;
    }
    
    function getIsOpen() public view returns (bool) {
        return isOpen;
    }
    
    function start() public onlyBy(listingAgent) {
        isOpen = true;
    }
    
    /**
    function getListing() public view 
    returns (bool _isOpen, PokerTable[] _allTables) {
        _isOpen = isOpen;
        _allTables = pokerRoom;
    }*/
    
}

**Comment by psychoplasma** [comment]
I've got the same error on Ubuntu 16.04LTS when I tried to sign a contract on MyEtherWallet with Ganache CLI v6.0.3 (ganache-core: 2.0.2)


> /usr/lib/node_modules/ganache-cli/build/cli.node.js:74142
> var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRO
> AssertionError: The field to must have byte length of 20
>     at FakeTransaction.setter [as to] (/usr/lib/node_modules/ganache-cli/build/cli.node.js:7369:9)
>     at /usr/lib/node_modules/ganache-cli/build/cli.node.js:7419:63
>     at Array.forEach (native)
>     at Object.exports.defineProperties (/usr/lib/node_modules/ganache-cli/build/cli.node.js:7418:14)
>     at FakeTransaction.Transaction (/usr/lib/node_modules/ganache-cli/build/cli.node.js:88365:13)
>     at FakeTransaction (/usr/lib/node_modules/ganache-cli/build/cli.node.js:20465:5)
>     at /usr/lib/node_modules/ganache-cli/build/cli.node.js:90587:14
>     at /usr/lib/node_modules/ganache-cli/build/cli.node.js:21982:5
>     at /usr/lib/node_modules/ganache-cli/build/cli.node.js:67500:5
>     at /usr/lib/node_modules/ganache-cli/build/cli.node.js:67866:14

**Comment by benjamincburns** [comment]
@printlnBTC & @psychoplasma this is fixed in current develop branch - please search past issues for more info.

**Comment by zazka1** [comment]
The problem still exists. I am trying to deploy contract and get the same error.

**Comment by psychoplasma** [comment]
I solve the problem by using MetaMask and Ganache-CLI. If this fits you, give a try please.

**Comment by benjamincburns** [comment]
@zazka1 what version of Ganache?

**Comment by zazka1** [comment]
@benjamincburns 1.0.2. It worked with ganache-cli v6.1.0-beta.2.
