### ISSUE TITLE
Closing Ganache window doesn't actually terminate the Ganache application

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/ganache#76]
## Issue Type

- [x] [Bug](https://github.com/trufflesuite/zircon/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] [Feature](https://github.com/trufflesuite/zircon/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

When I close the Ganache window I expected it to terminate the program. This doesn't occur.

I think if this is expected/desired behaviour, clicking the Ganache icon in the Dock should reopen the last-viewed page, as otherwise when you click the Ganache icon in the Dock, the only observable change is that the OS X top-of-screen drop-down menus change back to Ganache's menus. This isn't as ideal as if it had a whatever-the-OSX-equivalent-to-a-tray-icon-is, as in that case it could hide its icon from the dock altogether, but this is similar to how the WhatsApp application behaves and it didn't trigger this sort of surprise for me.

## Steps to reproduce

1) Run Ganache, if first time running it, click through past the stats collection opt in page
2) Close the window
3) Observe that Ganache top-of-screen menus are still present and Ganache icon is still found in dock

# Versions

Release candidate build of Ganache which @tcoulter published for internal testing.

- Platform: macOS High Sierra

**Comment by tcoulter** [comment]
> When I close the Ganache window I expected it to terminate the program. This doesn't occur.

This should be fixed now as of 1.0. Can you recheck?

**Comment by benjamincburns** [comment]
Still doesn't quit on window close on High Sierra.

My problem now, though :-D
